sites:
  - name: 'TechCrunch'
    sku: 'techcrunch'
    refresh_rate: 300
    categories:
      - name: 'Popular'
        sku: 'popular'
        url: 'https://techcrunch.com/popular/'
        xpath_links:
          - "//a[contains(@data-omni-sm, 'gbl_river_headline')]"
      - name: 'Bitcoin'
        sku: 'bitcoin'
        url: 'https://techcrunch.com/topic/subject/bitcoin/'
        xpath_links:
          - "//a[@data-omni-sm='gbl_river_headline,']"
      - name: 'Internet of Things'
        sku: 'iot'
        url: 'https://techcrunch.com/topic/subject/internet-of-things/'
        xpath_links:
          - "//a[@data-omni-sm='gbl_river_headline,']"
  - name: 'The Hacker News'
    sku: 'the_hacker_news'
    refresh_rate: 330
    categories:
      - name: 'Popular Stories'
        sku: 'popular_stories'
        url: 'http://thehackernews.com/'
        xpath_links:
          - "//div[@class='widget-content popular-posts']//a"
      - name: 'Tech'
        sku: 'tech'
        url: 'http://thehackernews.com/search/label/Technology%20News'
        xpath_links:
          - "//article[@class='post item module']//h2/a"
      - name: 'Hacking'
        sku: 'hacking'
        url: 'http://thehackernews.com/search/label/hacking%20news'
        xpath_links:
          - "//article[@class='post item module']//h2/a"
      - name: 'Spying'
        sku: 'spying'
        url: 'http://thehackernews.com/search/label/spying'
        xpath_links:
          - "//article[@class='post item module']//h2/a"

  - name: 'Net hr'
    sku: 'net_hr'
    rhash: '6919fd5eeb20f4'
    refresh_rate: 360
    categories:
      - name: 'Most Popular'
        sku: 'most_popular'
        url: 'http://www.net.hr'
        xpath_links:
          - "//div[contains(@class, 'tab_1')]//a"
      - name: 'Most Recent'
        sku: 'most_recent'
        url: 'http://www.net.hr'
        xpath_links:
          - "//div[contains(@class, 'tab_2')]//a"
      - name: 'Croatia'
        sku: 'croatia'
        url: 'http://net.hr/kategorija/danas/hrvatska/'
        xpath_links:
          - "//div[contains(@class, 'article-text')]/a"
      - name: 'World'
        sku: 'world'
        url: 'http://net.hr/kategorija/danas/svijet/'
        xpath_links:
          - "//div[contains(@class, 'article-text')]/a"
