AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Telegram News Bot

Globals:
  Function:
    Timeout: 3
Resources:
  TelegramNewsBotHandler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: lambda.handler
      Layers:
        - !Ref TelegramNewsBotLayer
      Runtime: ruby2.5
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Sid: SSMParameterReadByPathPolicy
              Effect: Allow
              Action:
                - 'ssm:GetParametersByPath'
              Resource:
                !Sub 'arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/telegramNewsBot/*'
      Events:
        Webhook:
          Type: Api
          Properties:
            Path: /webhook
            Method: post
  TelegramNewsBotLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: telegram-news-bot-dependencies
      Description: Bundled gems
      ContentUri: dependencies/
      CompatibleRuntimes:
      - ruby2.5
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain

Outputs:
  WebhookApi:
    Description: "API Gateway endpoint URL for Prod stage for TelegramNewsBotHandler function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook/"

  TelegramNewsBotHandler:
    Description: "TelegramNewsBotHandler ARN"
    Value: !GetAtt TelegramNewsBotHandler.Arn

  TelegramNewsBotHandlerIamRole:
    Description: "Implicit IAM Role created for TelegramNewsBotHandler"
    Value: !GetAtt TelegramNewsBotHandlerRole.Arn
